name: Build-and-Test-Fundamental-Backend
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.306'
      
      - name: Verify .NET installation
        run: dotnet --version
      
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear
      
      - name: Restore dependencies
        run: dotnet restore --force --verbosity normal
      
      - name: Build
        run: dotnet build --configuration Release --no-restore --verbosity normal
      
      - name: Run unit tests
        run: dotnet test --configuration Release --verbosity normal --no-build
      
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: "18"
      # - name: Deploy to Liara
      #   env:
      #     LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
      #   run: |
      #     npm i -g @liara/cli@5
      #     liara deploy --app="fundamental-api" --api-token="$LIARA_TOKEN" --no-app-logs --port=5000
